### ISSUE TITLE
Inventory weight formatted incorrectly

### ISSUE THREAD

**Issue by c6-dev** [alexbatalov/fallout1-re#5]
Not sure if this one is a vanilla bug or not, but after picking up supplies from the Brotherhood knight i am at 132/115 weight, but there are no penalties to movement speed and "you are overloaded" message does not appear.  
Trying to pick up an item from the ground correctly displays "you are at your maximum capacity" message however.

[SLOT07.zip](https://github.com/alexbatalov/fallout1-re/files/10526881/SLOT07.zip)

**Comment by alexbatalov** [comment]
There is no "overload" concept in Fallout 1 when in comes to running vs. walking. I've checked both 1.1 and 1.2. I've also checked grabbing items from the ground and looting containers - message "your are at your maximum capacity" appears as expected. It's been a while since I've played F1, remind me how did you get these supplies?

**Comment by c6-dev** [comment]
Oh, my bad, good to know!
When you get accepted as an initiate into the brotherhood, you are assigned a suit of armor and some ammo, which are received through dialogue with the supply knight in the hallway to the right.
I didn't keep a save before doing that unfortunately, but there is another opportunity to get supplies from him later, i can send a save when i reach that point.

**Comment by c6-dev** [comment]
https://fallout.wiki/wiki/Michael_(Brotherhood) - this is the knight that gives out equipment.

**Comment by c6-dev** [comment]
A different instance of receiving items through dialogue while over the carryweight limit - talk to the peasant and report that the quest is completed, he gives you a pistol. Looks like the behavior is exactly the same in vanilla, so this can be closed.
[SLOT09.zip](https://github.com/alexbatalov/fallout1-re/files/10527019/SLOT09.zip)

One minor discrepancy i noticed is that the inventory weight in vanilla is displayed as `Total Wt: 122` and in RE it's `Total Wt: 122/115`.
